name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Go 环境（使用官方 GitHub Action）
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # 验证 Go 安装
      - name: Verify Go installation
        run: |
          echo "Go version:"
          go version
          echo "Go environment:"
          go env

      # 检查 Go 版本
      - name: Check Go version and subcommands
        run: |
          go version
          go help mod

      # 启用 Go 模块模式
      - name: Enable Go module mode
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      # 初始化并清理 Go 模块
      - name: Initialize and tidy Go module
        run: |
          cd $GITHUB_WORKSPACE
          go mod tidy

      # 安装 Wails CLI
      - name: Install Wails CLI
        run: |
          mkdir -p $HOME/go/bin
          export GOBIN=$HOME/go/bin
          echo "export PATH=$GOBIN:$PATH" >> $GITHUB_ENV
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 验证 Wails 安装
      - name: Verify Wails installation
        run: |
          echo "Checking Wails installation:"
          which wails
          wails --version

      # 构建 Windows 平台可执行文件
      - name: Build Windows EXE
        run: wails build -platform windows/amd64

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
