name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 清理并重新安装 Go
      - name: Ensure fresh Go installation
        run: |
          sudo rm -rf /usr/local/go
          curl -LO https://golang.org/dl/go1.20.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
          echo "export PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV

      # 验证 Go 安装
      - name: Verify Go installation
        run: |
          echo "Go version:"
          go version
          echo "Go environment:"
          go env

      # 启用 Go 模块模式
      - name: Enable Go module mode
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      # 初始化 Go 模块
      - name: Initialize Go module
        run: |
          cd $GITHUB_WORKSPACE
          if [ ! -f go.mod ]; then
            echo "No go.mod found, initializing Go module."
            go mod init example.com/myproject
          fi
          go mod tidy

      # 安装 Wails CLI
      - name: Install Wails CLI
        run: |
          mkdir -p $HOME/go/bin
          export GOBIN=$HOME/go/bin
          echo "export PATH=$GOBIN:$PATH" >> $GITHUB_ENV
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 构建 Windows 平台可执行文件
      - name: Build Windows EXE
        run: |
          # Ensure the environment variables are reloaded for this step
          source $GITHUB_ENV
          wails build -platform windows/amd64

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
