name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装指定版本的 Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # 验证 Go 安装
      - name: Check Go installation
        run: |
          echo "Go version:"
          go version
          echo "Go root:"
          go env GOROOT
          echo "Go path:"
          go env GOPATH
          echo "Environment PATH:"
          echo $PATH

      # 启用模块模式
      - name: Enable Go module mode
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      # 初始化 Go 模块
      - name: Initialize Go module
        run: |
          if [ ! -f go.mod ]; then
            echo "No go.mod found, initializing Go module."
            go mod init example.com/myproject
          fi
          go mod tidy

      # 安装 Wails CLI
      - name: Install Wails CLI
        run: |
          export GOBIN=$HOME/go/bin
          mkdir -p $GOBIN
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 构建 Windows 平台可执行文件
      - name: Build Windows EXE
        run: wails build -platform windows/amd64

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
