name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 确保 Go 安装是最新的
      - name: Install Go
        run: |
          sudo rm -rf /usr/local/go
          curl -LO https://golang.org/dl/go1.20.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
          echo "export PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "GOBIN=$HOME/go/bin" >> $GITHUB_ENV

      # 确保 Go 环境配置正确
      - name: Verify Go installation
        run: |
          echo "Go version:"
          go version
          echo "Go environment:"
          go env

      # 缓存 Go 模块依赖
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-mod-

      # 安装 Wails CLI
      - name: Install Wails CLI
        run: |
          mkdir -p $HOME/go/bin
          export GOBIN=$HOME/go/bin
          export PATH=$GOBIN:$PATH
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 确保 `go.mod` 和 `wails.json` 文件正确链接
      - name: Create symlink for go.mod and wails.json
        run: |
          ln -sf $GITHUB_WORKSPACE/CryptoBox/go.mod $GITHUB_WORKSPACE/go.mod
          ln -sf $GITHUB_WORKSPACE/CryptoBox/wails.json $GITHUB_WORKSPACE/wails.json

      # 更新 Go 模块并安装 Wails 依赖
      - name: Ensure Go modules and Wails dependencies are up-to-date
        run: |
          go mod tidy
          go get github.com/wailsapp/wails/v2@v2.9.2

      # 确认 go.mod 文件已正确更新
      - name: Verify go.mod and go.sum
        run: |
          cat go.mod
          cat go.sum

      # 构建 Windows 平台可执行文件
      - name: Build Windows EXE
        run: |
          export PATH=$HOME/go/bin:$PATH
          cd $GITHUB_WORKSPACE  # 确保处于项目根目录
          wails build -platform windows/amd64

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
