name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 Go
      - name: Install Go
        run: |
          sudo rm -rf /usr/local/go
          curl -LO https://golang.org/dl/go1.20.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
          echo "export PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "GOBIN=$HOME/go/bin" >> $GITHUB_ENV

      # 安装 Wails CLI
      - name: Install Wails CLI
        run: |
          mkdir -p $HOME/go/bin
          export GOBIN=$HOME/go/bin
          export PATH=$GOBIN:$PATH
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 更新 go.mod 以使用最新的 Wails 版本
      - name: Update go.mod to use Wails v2.9.2
        run: |
          cd $GITHUB_WORKSPACE/CryptoBox
          sed -i 's/github.com\/wailsapp\/wails v2.3.1/github.com\/wailsapp\/wails\/v2 v2.9.2/' go.mod
          go mod tidy

      # 创建软链接，将 CryptoBox/codebox 目录链接到根目录
      - name: Create symlink for codebox
        run: |
          ln -sf $GITHUB_WORKSPACE/CryptoBox/codebox $GITHUB_WORKSPACE/codebox

      # 创建软链接，将 main.go 和 app.go 链接到项目根目录
      - name: Create symlink for Go files
        run: |
          ln -sf $GITHUB_WORKSPACE/CryptoBox/main.go $GITHUB_WORKSPACE/main.go
          ln -sf $GITHUB_WORKSPACE/CryptoBox/app.go $GITHUB_WORKSPACE/app.go

      # 创建软链接，将 go.mod 和 wails.json 文件链接到根目录
      - name: Create symlink for go.mod and wails.json
        run: |
          ln -sf $GITHUB_WORKSPACE/CryptoBox/go.mod $GITHUB_WORKSPACE/go.mod
          ln -sf $GITHUB_WORKSPACE/CryptoBox/wails.json $GITHUB_WORKSPACE/wails.json

      # 创建软链接，将 package.json 从 CryptoBox 目录链接到根目录
      - name: Create symlink for package.json
        run: |
          ln -sf $GITHUB_WORKSPACE/CryptoBox/package.json $GITHUB_WORKSPACE/package.json

      # 安装 frontend 依赖（包括 father）
      - name: Install frontend dependencies
        run: |
          cd $GITHUB_WORKSPACE/CryptoBox/frontend
          npm install

      # 确保 Go 模块和依赖已更新
      - name: Ensure Go modules and dependencies are updated
        run: |
          cd $GITHUB_WORKSPACE/CryptoBox
          go mod tidy
          go mod vendor

      # 构建 Windows 平台可执行文件
      - name: Build Windows EXE
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$HOME/go/bin:$PATH
          wails build -platform windows/amd64

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
