name: Build Wails Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Enable Go module mode
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Check Go version
        run: go version

      - name: Initialize Go module
        run: |
          if [ ! -f go.mod ]; then
            echo "No go.mod found, initializing Go module."
            go mod init example.com/myproject
          fi
          go mod tidy

      - name: Install Wails CLI
        run: |
          export GOBIN=$HOME/go/bin
          mkdir -p $GOBIN
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
        env:
          GOROOT: /opt/hostedtoolcache/go/1.20.0/x64
          GOPATH: ${{ runner.temp }}/go

      - name: Add GOBIN to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build Windows EXE
        run: wails build -platform windows/amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-Executable
          path: build/bin/*.exe
